import {
  BookOpen,
  RefreshCcw,
  Wifi,
  Newspaper,
  Globe,
  User,
  Headphones,
  Clock,
  CheckCircle2,
  SwitchCamera,
  Sparkles,
  Wind,
  Monitor,
  Users,
} from "lucide-react";

export const features = [
  {
    icon: BookOpen,
    title: "Nearby Library Seat Booking",
    desc: "Book seats instantly in libraries near your location.",
  },
  {
    icon: CheckCircle2,
    title: "Free Trial",
    desc: "Try before you decide – free trial for every student.",
  },
  {
    icon: SwitchCamera,
    title: "Switch Library Anytime",
    desc: "Change library anytime without extra charges.",
  },
  {
    icon: Globe,
    title: "No Dependency",
    desc: "One membership, access to multiple verified libraries.",
  },
  {
    icon: Users,
    title: "Pan-India Access",
    desc: "Study at any listed library across India after booking.",
  },
  {
    icon: Newspaper,
    title: "Daily Newspapers",
    desc: "Get daily newspapers in every library (Hindi + English).",
  },
  {
    icon: Sparkles,
    title: "Monthly Current Affairs",
    desc: "Free curated current affairs for exam prep.",
  },
  {
    icon: Wind,
    title: "AC Study Environment",
    desc: "Noise-free, comfortable and air-conditioned halls.",
  },
  {
    icon: Wifi,
    title: "High-Speed WiFi",
    desc: "Reliable internet for online study & mock tests.",
  },
  {
    icon: Monitor,
    title: "Comfortable Seating",
    desc: "Ergonomic chairs & spacious desks for long hours.",
  },
  {
    icon: User,
    title: "Personal Manager",
    desc: "Dedicated manager for booking & library support.",
  },
  {
    icon: RefreshCcw,
    title: "Quick Problem Solve",
    desc: "Any library-related issue solved quickly.",
  },
  {
    icon: Headphones,
    title: "24×7 Support",
    desc: "Get help anytime through call or chat.",
  },
  {
    icon: Clock,
    title: "And More...",
    desc: "Lockers, clean washrooms, and extra facilities.",
  },
];

export const reviews = [
  { name: "Amit", text: "Best library for students!", stars: 5 },
  { name: "Sara", text: "Great environment and staff.", stars: 4 },
  { name: "John", text: "WiFi and resources are excellent.", stars: 5 },
  { name: "Priya", text: "Loved the free trial offer!", stars: 4 },
  { name: "Rahul", text: "Helped me clear my exam.", stars: 5 },
  { name: "Fatima", text: "Clean and peaceful place.", stars: 5 },

  // ---- extra 50 reviews ----
  {
    name: "Karan",
    text: "Quiet and comfortable for long study sessions.",
    stars: 5,
  },
  { name: "Neha", text: "Friendly staff and well-organized books.", stars: 4 },
  {
    name: "Ravi",
    text: "Perfect place to focus without distractions.",
    stars: 5,
  },
  { name: "Meera", text: "Spacious seating and good lighting.", stars: 5 },
  { name: "Sandeep", text: "Affordable membership plans.", stars: 4 },
  {
    name: "Alok",
    text: "Best spot to prepare for competitive exams.",
    stars: 5,
  },
  { name: "Nisha", text: "Air-conditioned and very comfortable.", stars: 5 },
  { name: "Vivek", text: "Love the peaceful vibes here.", stars: 4 },
  { name: "Komal", text: "Very supportive environment.", stars: 5 },
  { name: "Rohit", text: "Internet speed is fast and reliable.", stars: 5 },
  { name: "Sneha", text: "Good parking facility near the library.", stars: 4 },
  { name: "Arjun", text: "I could finally focus on my UPSC prep.", stars: 5 },
  { name: "Pooja", text: "Best library in the city, hands down.", stars: 5 },
  { name: "Ishaan", text: "Plenty of charging points for laptops.", stars: 5 },
  { name: "Ayesha", text: "Silent study rooms are amazing.", stars: 5 },
  { name: "Mohit", text: "The ambiance really motivates me.", stars: 5 },
  { name: "Simran", text: "Membership is worth every penny.", stars: 5 },
  { name: "Deepak", text: "Perfectly maintained library.", stars: 4 },
  { name: "Anjali", text: "Hygienic and very well cleaned daily.", stars: 5 },
  { name: "Harsh", text: "Books collection is really vast.", stars: 5 },
  { name: "Reema", text: "Staff is polite and helpful.", stars: 4 },
  { name: "Kabir", text: "Helped me stay disciplined.", stars: 5 },
  { name: "Shalini", text: "Library timing is very flexible.", stars: 5 },
  { name: "Aarav", text: "Such a positive environment to study.", stars: 5 },
  {
    name: "Divya",
    text: "Neat washrooms and drinking water facility.",
    stars: 4,
  },
  { name: "Nikhil", text: "Tables and chairs are very comfortable.", stars: 5 },
  { name: "Maya", text: "Good value for students on a budget.", stars: 5 },
  { name: "Tanya", text: "Loved the quiet reading zones.", stars: 5 },
  { name: "Ashish", text: "Really supportive for group studies.", stars: 4 },
  { name: "Ritika", text: "Peaceful place, feels like home.", stars: 5 },
  {
    name: "Manoj",
    text: "Lighting is perfect for late night study.",
    stars: 5,
  },
  { name: "Shreya", text: "Perfect place to prepare for NEET.", stars: 5 },
  { name: "Zoya", text: "Calm atmosphere and clean desks.", stars: 5 },
  { name: "Gaurav", text: "Affordable and worth it.", stars: 4 },
  { name: "Lavanya", text: "Best place for self-study.", stars: 5 },
  { name: "Prateek", text: "Silent and motivating environment.", stars: 5 },
  { name: "Chirag", text: "Very organized and clean.", stars: 4 },
  { name: "Payal", text: "Focus level here is unmatched.", stars: 5 },
  {
    name: "Suhana",
    text: "Cafeteria nearby is helpful during breaks.",
    stars: 5,
  },
  { name: "Dev", text: "Helped me crack my SSC exam.", stars: 5 },
  { name: "Nandini", text: "Super friendly atmosphere.", stars: 4 },
  { name: "Aditya", text: "Really like the modern design.", stars: 5 },
  { name: "Mohan", text: "Peaceful environment for research work.", stars: 5 },
  { name: "Kavya", text: "The interior is very cozy.", stars: 4 },
  { name: "Ansh", text: "The perfect blend of peace and focus.", stars: 5 },
  { name: "Vidhi", text: "I can study here for 8 hours easily.", stars: 5 },
  { name: "Ramesh", text: "Well-ventilated and fresh environment.", stars: 4 },
  { name: "Sonia", text: "Highly recommend for all students.", stars: 5 },
  { name: "Yash", text: "Absolutely love studying here daily.", stars: 5 },
  { name: "Bhavna", text: "Best part is the discipline inside.", stars: 5 },
  {
    name: "Parth",
    text: "Great place to clear your mind and focus.",
    stars: 5,
  },
];

export const librariesdata = [
  {
    id: 1,
    name: "Serenity Study Centre",
    address:
      "B, 1st floor, 4th Cross Road, 8th Main Rd, Hampi Nagar, RPC Layout, Bengaluru, Karnataka 560104",
    image1: "/images/librariesimages/firstlib/image1libraries.jpg",
    image2: "/images/librariesimages/firstlib/image2libraries.jpg",
    image3: "/images/librariesimages/firstlib/image3libraries.jpg",
    image4: "/images/librariesimages/firstlib/image4libraries.jpg",
    rating: 4.5,
    reviews: 120,
    facilities: ["WiFi", "Quiet Study Space", "AC", "Seats (All Day)"],
    fee: "₹1500/month",
    shiftHours: "12:00 - 23:00",
    seatAvailability: "20/50 Seats Available",
  },
  {
    id: 2,
    name: "Genius Library",
    address: "Bengaluru, Karnataka, India, Vijayanagar East, 560040",
    image1: "/images/librariesimages/secondlib/image1libraries.jpg",
    image2: "/images/librariesimages/secondlib/image2libraries.jpg",
    image3: "/images/librariesimages/secondlib/image3libraries.jpg",
    image4: "/images/librariesimages/secondlib/image4libraries.jpg",
    rating: 4.2,
    reviews: 85,
    facilities: ["WiFi", "AC", "Cafeteria", "Lockers"],
    fee: "₹1200/month",
    shiftHours: "09:00-21:00",
    seatAvailability: "50 Seats Available",
  },
  {
    id: 3,
    name: "Vishisht Study Space",
    address: "Bengaluru, Karnataka, India",
    image1: "/images/librariesimages/thirdlib/image1libraries.jpg",
    image2: "/images/librariesimages/thirdlib/image2libraries.jpg",
    image3: "/images/librariesimages/thirdlib/image3libraries.jpg",
    image4: "/images/librariesimages/thirdlib/image4libraries.jpg",
    rating: 4.2,
    reviews: 85,
    facilities: ["WiFi", "AC", "Cafeteria", "Lockers"],
    fee: "₹1200/month",
    shiftHours: "09:00-21:00",
    seatAvailability: "80 Seats Available",
  },
  {
    id: 4,
    name: "Visionary Study Zone Unit-2",
    address: "Bengaluru, Karnataka, India",
    image1: "/images/librariesimages/fourlib/image1libraries.jpg",
    image2: "/images/librariesimages/fourlib/image2libraries.jpg",
    image3: "/images/librariesimages/fourlib/image3libraries.jpg",
    image4: "/images/librariesimages/fourlib/image4libraries.jpg",
    rating: 4.2,
    reviews: 85,
    facilities: ["WiFi", "AC", "Cafeteria", "Lockers"],
    fee: "₹1000/month",
    shiftHours: "09:00-21:00",
    seatAvailability: "30 Seats Available",
  },
  {
    id: 5,
    name: "Reading Room Library",
    address: "Bengaluru, Karnataka, India",
    image1: "/images/librariesimages/fivelib/image1libraries.jpg",
    image2: "/images/librariesimages/fivelib/image2libraries.jpg",
    image3: "/images/librariesimages/fivelib/image3libraries.jpg",
    image4: "/images/librariesimages/fivelib/image4libraries.jpg",
    rating: 4.2,
    reviews: 85,
    facilities: ["WiFi", "AC", "Cafeteria", "Lockers"],
    fee: "₹1200/month",
    shiftHours: "09:00-21:00",
    seatAvailability: "80 Seats Available",
  },
  {
    id: 6,
    name: "Visionary Study Zone Unit-2",
    address: "Bengaluru, Karnataka, India",
    image1: "/images/librariesimages/fourlib/image1libraries.jpg",
    image2: "/images/librariesimages/fourlib/image2libraries.jpg",
    image3: "/images/librariesimages/fourlib/image3libraries.jpg",
    image4: "/images/librariesimages/fourlib/image4libraries.jpg",
    rating: 4.2,
    reviews: 85,
    facilities: ["WiFi", "AC", "Cafeteria", "Lockers"],
    fee: "₹1000/month",
    shiftHours: "09:00-21:00",
    seatAvailability: "30 Seats Available",
  },
  {
    id: 7,
    name: "Genius Library",
    address: "Bengaluru, Karnataka, India, Vijayanagar East, 560040",
    image1: "/images/librariesimages/secondlib/image1libraries.jpg",
    image2: "/images/librariesimages/secondlib/image2libraries.jpg",
    image3: "/images/librariesimages/secondlib/image3libraries.jpg",
    image4: "/images/librariesimages/secondlib/image4libraries.jpg",
    rating: 4.2,
    reviews: 85,
    facilities: ["WiFi", "AC", "Cafeteria", "Lockers"],
    fee: "₹1200/month",
    shiftHours: "09:00-21:00",
    seatAvailability: "50 Seats Available",
  },
  {
    id: 8,
    name: "Reading Room Library",
    address: "Bengaluru, Karnataka, India",
    image1: "/images/librariesimages/fivelib/image1libraries.jpg",
    image2: "/images/librariesimages/fivelib/image2libraries.jpg",
    image3: "/images/librariesimages/fivelib/image3libraries.jpg",
    image4: "/images/librariesimages/fivelib/image4libraries.jpg",
    rating: 4.2,
    reviews: 85,
    facilities: ["WiFi", "AC", "Cafeteria", "Lockers"],
    fee: "₹1200/month",
    shiftHours: "09:00-21:00",
    seatAvailability: "80 Seats Available",
  },
];

// export const prepLibraries = [
//   {
//     id: 1,
//     name: "Prep Master Library",
//     address:
//       "11/105, 1st Floor, near Ansal Tower, Block J, Rajouri Garden Extension, Subhash Nagar, Delhi-110027",
//     image: "/images/heroimage.jpg",
//     rating: 4.0,
//     reviews: 50,
//     facilities: ["WiFi", "Quiet Study Space", "AC", "Seats (All Day)"],
//     fee: "₹1000/month",
//     shiftHours: "08:00-20:00",
//   },
//   {
//     id: 4,
//     name: "Aarambh Pustakalya, Adhchini",
//     address: "Adhchini Village, South Delhi",
//     image: "/images/heroimage.jpg", // (placeholder, not exact Adhchini image)
//     rating: 4.0,
//     reviews: 40,
//     facilities: ["24/7 Study Room", "WiFi", "AC", "Lockers", "Cafeteria"],
//     fee: "₹1000/month",
//     shiftHours: "24 hours / 3 shifts",
//   },
//   {
//     id: 5,
//     name: "Aarambh Library, Rohini (G-Block, Sector 11)",
//     address: "Rohini G-Block, Sector 11, Delhi",
//     image: "/images/heroimage.jpg",
//     rating: 4.1,
//     reviews: 45,
//     facilities: ["Study Seats", "WiFi", "Ergonomic Chairs", "Lockers", "AC"],
//     fee: "₹1000/month",
//     shiftHours: "Multiple Shifts",
//   },
//   {
//     id: 3,
//     name: "Dr. Vijay Pal Memorial Library",
//     address:
//       "Plot No. 8, Local Shopping Centre, Block C-7, Keshav Puram, Delhi-110035",
//     image: "/images/heroimage.jpg", // अभी कोई verified public image नहीं मिला
//     rating: 4.3,
//     reviews: 80,
//     facilities: [
//       "Reference Books",
//       "Quiet Environment",
//       "AC Reading Room",
//       "Seats for Exam Aspirants",
//     ],
//     fee: "Membership Fee",
//     shiftHours: "07:30-21:30",
//   },
// ];
